from app.scoring import confidence_word


def generate_label(attribution: str, confidence: float) -> str:
    """Map attribution + confidence to the plain-language transparency
    label shown to readers (spec §3). Confidence percentage is embedded
    so the text differs between high- and low-confidence results."""
    pct = round(confidence * 100)
    word = confidence_word(attribution, confidence)

    if attribution == "likely_ai":
        return (
            f"🤖 Likely AI-generated. "
            f"Our analysis suggests this text was probably created with the help "
            f"of an AI tool (confidence: {word}, {pct}%). This is an automated "
            f"estimate, not a certainty — the creator can request a review if "
            f"they disagree."
        )

    if attribution == "likely_human":
        return (
            f"✍️ Likely human-written. "
            f"Our analysis suggests this text was probably written by a person "
            f"(confidence: {word}, {pct}%). This is an automated estimate, "
            f"not a guarantee."
        )

    # uncertain
    return (
        f"❓ Origin unclear. "
        f"We couldn't confidently determine whether this text was written by a "
        f"person or generated by AI (confidence: {word}). Please treat the "
        f"origin as unknown. Human authorship is entirely plausible."
    )