import os
import json
import re
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
MODEL = "llama-3.3-70b-versatile"

LLM_SYSTEM_PROMPT = """You are a forensic text-attribution analyst. \
Assess whether a piece of writing was most likely written by a human or \
generated by an AI language model.

Judge holistic semantic and stylistic signals: naturalness of voice, \
specificity of lived detail, originality of phrasing, presence of generic \
"AI-sounding" transitions, and over-smoothness.

Respond with ONLY a JSON object, no prose, in exactly this form:
{"ai_likelihood": <float 0.0-1.0>, "rationale": "<one short sentence>"}

ai_likelihood = probability the text is AI-generated.
0.0 = certainly human, 1.0 = certainly AI."""


def llm_signal(text: str) -> dict:
    """
    Signal 1 — semantic/stylistic judgment via Groq LLM.
    Returns {"ai_likelihood": float 0-1, "rationale": str, "signal": "llm"}.
    Higher ai_likelihood => more AI-like.
    """
    resp = _client.chat.completions.create(
        model=MODEL,
        temperature=0.0,
        messages=[
            {"role": "system", "content": LLM_SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    raw = resp.choices[0].message.content.strip()

    # Robustly extract the JSON object even if the model adds stray text.
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if not match:
        return {"ai_likelihood": 0.5,
                "rationale": "Unparseable LLM output; defaulting to uncertain.",
                "signal": "llm"}

    try:
        data = json.loads(match.group(0))
    except json.JSONDecodeError:
        return {"ai_likelihood": 0.5,
                "rationale": "Malformed JSON from model; defaulting to uncertain.",
                "signal": "llm"}

    score = float(data.get("ai_likelihood", 0.5))
    score = max(0.0, min(1.0, score))  # clamp to [0,1]

    return {
        "ai_likelihood": round(score, 4),
        "rationale": data.get("rationale", ""),
        "signal": "llm",
    }
