import os
import json
import re
import statistics
from groq import Groq
from dotenv import load_dotenv


load_dotenv()

_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
MODEL = "llama-3.3-70b-versatile"

LLM_SYSTEM_PROMPT = """You are a forensic text-attribution analyst. \
Assess whether a piece of writing was most likely written by a human or \
generated by an AI language model.

Judge holistic semantic and stylistic signals: naturalness of voice, \
specificity of lived detail, originality of phrasing, presence of generic \
"AI-sounding" transitions, and over-smoothness.

Respond with ONLY a JSON object, no prose, in exactly this form:
{"ai_likelihood": <float 0.0-1.0>, "rationale": "<one short sentence>"}

ai_likelihood = probability the text is AI-generated.
0.0 = certainly human, 1.0 = certainly AI."""


def llm_signal(text: str) -> dict:
    """
    Signal 1 — semantic/stylistic judgment via Groq LLM.
    Returns {"ai_likelihood": float 0-1, "rationale": str, "signal": "llm"}.
    Higher ai_likelihood => more AI-like.
    """
    resp = _client.chat.completions.create(
        model=MODEL,
        temperature=0.0,
        messages=[
            {"role": "system", "content": LLM_SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    raw = resp.choices[0].message.content.strip()

    # Robustly extract the JSON object even if the model adds stray text.
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if not match:
        return {"ai_likelihood": 0.5,
                "rationale": "Unparseable LLM output; defaulting to uncertain.",
                "signal": "llm"}

    try:
        data = json.loads(match.group(0))
    except json.JSONDecodeError:
        return {"ai_likelihood": 0.5,
                "rationale": "Malformed JSON from model; defaulting to uncertain.",
                "signal": "llm"}

    score = float(data.get("ai_likelihood", 0.5))
    score = max(0.0, min(1.0, score))  # clamp to [0,1]

    return {
        "ai_likelihood": round(score, 4),
        "rationale": data.get("rationale", ""),
        "signal": "llm",
    }

def _split_sentences(text: str):
    # Split on sentence-ending punctuation followed by whitespace.
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    return [p for p in parts if p.strip()]


def _tokenize_words(text: str):
    return re.findall(r"\b\w+\b", text.lower())


def stylometric_signal(text: str) -> dict:
    """
    Signal 2 — structural variability via pure-Python stylometrics.
    Returns {"ai_likelihood": float 0-1, "metrics": {...}, "signal": "stylometric"}.
    Higher ai_likelihood => more uniform => more AI-like.
    """
    sentences = _split_sentences(text)
    words = _tokenize_words(text)

    # Guard: very short text is unreliable -> push toward 0.5 (uncertain).
    if len(words) < 20 or len(sentences) < 2:
        return {
            "ai_likelihood": 0.5,
            "metrics": {"note": "Text too short for reliable stylometry."},
            "signal": "stylometric",
        }

    # --- Metric 1: Sentence-length variance (uniformity) ---------------
    sent_lengths = [len(_tokenize_words(s)) for s in sentences]
    mean_len = statistics.mean(sent_lengths)
    stdev_len = statistics.pstdev(sent_lengths)
    # Coefficient of variation: low CV = uniform = AI-like.
    cv = (stdev_len / mean_len) if mean_len > 0 else 0
    # Map CV to uniformity score: CV ~0.0 -> 1.0 (AI), CV >=0.6 -> 0.0 (human).
    uniformity_score = max(0.0, min(1.0, 1.0 - (cv / 0.6)))

    # --- Metric 2: Type-token ratio (vocabulary diversity) -------------
    ttr = len(set(words)) / len(words)
    # AI text often has *moderate-to-high* but smooth TTR; humans vary more.
    # Here we treat very high diversity as human-leaning. TTR ~0.4 -> AI-ish,
    # TTR ~0.7+ -> human-ish. Invert and scale.
    ttr_ai_score = max(0.0, min(1.0, (0.75 - ttr) / 0.35))

    # --- Metric 3: Punctuation density / variety -----------------------
    punct = re.findall(r"[,;:\-—()\"'!?]", text)
    punct_density = len(punct) / len(words)
    punct_variety = len(set(punct))
    # Sparse, low-variety punctuation -> smoother -> AI-like.
    # Density ~0.02 & low variety -> AI; richer punctuation -> human.
    punct_ai_score = max(0.0, min(1.0, 1.0 - (punct_density / 0.12)))
    if punct_variety >= 4:
        punct_ai_score *= 0.7  # rich variety pulls toward human

    # --- Combine the three sub-metrics into one signal score -----------
    # Weighted: sentence uniformity is the strongest stylometric tell.
    stylo_score = (0.50 * uniformity_score
                   + 0.30 * ttr_ai_score
                   + 0.20 * punct_ai_score)
    stylo_score = round(max(0.0, min(1.0, stylo_score)), 4)

    return {
        "ai_likelihood": stylo_score,
        "metrics": {
            "sentence_count": len(sentences),
            "mean_sentence_length": round(mean_len, 2),
            "sentence_length_cv": round(cv, 3),
            "type_token_ratio": round(ttr, 3),
            "punctuation_density": round(punct_density, 3),
            "punctuation_variety": punct_variety,
            "uniformity_score": round(uniformity_score, 3),
            "ttr_ai_score": round(ttr_ai_score, 3),
            "punct_ai_score": round(punct_ai_score, 3),
        },
        "signal": "stylometric",
    }
def repetition_signal(text: str) -> dict:
    """
    Signal 3 — repetition/burstiness heuristic.
    Measures repeated bigrams and repeated sentence-opening words.
    Returns {"ai_likelihood": float 0-1, "metrics": {...}, "signal": "repetition"}.
    Higher => more repetitive => more AI-like.
    """
    words = _tokenize_words(text)
    sentences = _split_sentences(text)

    if len(words) < 20 or len(sentences) < 2:
        return {
            "ai_likelihood": 0.5,
            "metrics": {"note": "Text too short for reliable repetition analysis."},
            "signal": "repetition",
        }

    # --- Repeated bigrams ---------------------------------------------
    bigrams = [(words[i], words[i + 1]) for i in range(len(words) - 1)]
    unique_bigrams = len(set(bigrams))
    bigram_repetition = 1.0 - (unique_bigrams / len(bigrams))

    # --- Repeated sentence openers ------------------------------------
    openers = [_tokenize_words(s)[0] for s in sentences if _tokenize_words(s)]
    unique_openers = len(set(openers))
    opener_repetition = 1.0 - (unique_openers / len(openers)) if openers else 0.0

    # --- Combine with a NEUTRAL baseline ------------------------------
    # Absence of repetition is NOT evidence of human authorship, so low
    # repetition stays ~0.5 (the signal abstains). Only *detected*
    # repetition pushes the score upward toward AI.
    rep_raw = (0.6 * bigram_repetition + 0.4 * opener_repetition)
    rep_score = 0.5 + min(0.5, rep_raw * 2.0)
    rep_score = round(max(0.0, min(1.0, rep_score)), 4)

    return {
        "ai_likelihood": rep_score,
        "metrics": {
            "bigram_repetition": round(bigram_repetition, 3),
            "opener_repetition": round(opener_repetition, 3),
            "unique_bigrams": unique_bigrams,
            "unique_openers": unique_openers,
        },
        "signal": "repetition",
    }